### ISSUE TITLE
不错的插件 

### ISSUE THREAD

**Issue by redleafnew** [wileyyugioh/zotmoov#1]
正好需要，有一个zotero插件开发团队微信群，茉莉花的作者也在里面，有兴趣加入吗？

**Comment by redleafnew** [comment]
https://github.com/Theigrams/zotero-pdf-custom-rename
这两个配合起来更好了。

**Comment by llity** [comment]
@redleafnew 能完美代替zotfile吗？谢谢

**Comment by llity** [comment]
搞个合并项目吧

**Comment by redleafnew** [comment]
现在还不能

**Comment by llity** [comment]
> 现在还不能

就等这个功能才能平滑过度到zotero 7了。附加 分类/重命名 加上 链接

**Comment by llity** [comment]
等你们的好消息，zotfile rebuild一下不知道咋样

**Comment by redleafnew** [comment]
> 等你们的好消息，zotfile rebuild一下不知道咋样

Zotero 6和7差别很大，基于不同的Firefox版本，估计希望不大了。

**Comment by llity** [comment]
确实需要全新的拓展才能升级到zotero7，官方应该是不支持的，相当于杀死自己的同步空间订阅功能。
