### ISSUE TITLE
[FR] Move to the subfolder relative to the root path

### ISSUE THREAD

**Issue by github-young** [wileyyugioh/zotmoov#11]
Thanks for this life-saving plugin when the `ZotFile`/`Zotero-file` is not available in Zotero 7.

I am thinking if you have time to implement the following behavior like `ZotFile` does:
Move the PDF attachment into the subfolder relative to the root path specified in the settings.

![图片](https://github.com/wileyyugioh/zotmoov/assets/19162282/628e41fe-f1ff-4648-b754-3b436002ca16)

For example, I set the location for the PDF files as ``/pdf/root/path`` in the settings of this plugin, and I have one item added in the ``Course-ELEC5110`` subfolder in Zotero. Both `ZotFile` and `Zotero-Files` can move the PDF file into ``/pdf/root/path/Course-ELEC5110``. However, this plugin moves the PDF file into ``/pdf/root/path`` instead.

Thank you.

**Comment by wileyyugioh** [comment]
Can you try the new feature [here](https://github.com/wileyyugioh/zotmoov/releases/tag/0.0.3b1)?

As a heads up, if a file belongs to multiple collections it will be only moved to one folder.

**Comment by github-young** [comment]
It works! Thank you very much!
