### ISSUE TITLE
 "move files to collection subdirectory" does not support Chinese ?

### ISSUE THREAD

**Issue by xinyeCH** [wileyyugioh/zotmoov#12]
Thanks for your great work!

I have a question. Does the option of "move files to collection subdirectory" support Chinese. When my file path contains Chinese, the subdirectory can not be created successfully but only the underscore。
<img width="214" alt="image" src="https://github.com/wileyyugioh/zotmoov/assets/20532214/2df2a034-bbc6-4349-aa01-ce5b0b8d86ed">

**Comment by vanish87** [comment]
It seems to handle the a-z 0-9 only

` collection_name = collection_name.replace(/[^a-z0-9]/gi, '_'); // Convert to file safe string`

> /[^a-z0-9]/gi

**Comment by wileyyugioh** [comment]
Yes, I am working on a fix to that.

**Comment by wileyyugioh** [comment]
@xinyeCH can you please try the new update https://github.com/wileyyugioh/zotmoov/releases/tag/0.0.3b7

**Comment by xinyeCH** [comment]
> @xinyeCH can you please try the new update https://github.com/wileyyugioh/zotmoov/releases/tag/0.0.3b7

Thank you very much for the fix, It works.
