### ISSUE TITLE
zotmoov on group libraries?

### ISSUE THREAD

**Issue by yildizanil** [wileyyugioh/zotmoov#15]
Zotmoov works efficiently on personal libraries (default _My Library_ on Zotero), but I cannot manage to move files automatically for group libraries. Is this a known missing functionality?

Thanks a lot

**Comment by wileyyugioh** [comment]
Since ZotMoov relies on linked files for its core functionality, being able to move files in group libraries is not possible. However, it should be fine to make a backup of the files using the copy file behavior.
