### ISSUE TITLE
Select which type of attachment to store

### ISSUE THREAD

**Issue by mariashinoto** [wileyyugioh/zotmoov#16]
Zotmoov works great. However, there is uncertainty about which attachments are stored and which are not. And I think I would only like to have PDFs stored outside of Zotero. 

The background is that the Zotero parent item can hold notes and other files with additional information. Some entries only have snapshots (HTML).

Zotmoov does not seem to export and link the notes, but it exports and links HTML files and snapshots besides PDFs. I would like to have these in Zotero; only PDFs that follow the naming convention for PDFs in Zotero should be exported. 

Also, I think epubs can be read in Zotero now; I am not yet bothered about them, but they might be treated like PDFs as well.

**Comment by wileyyugioh** [comment]
I am planning to add a table in the setting where you can add/remove the automatically moved file extensions

**Comment by wileyyugioh** [comment]
@mariashinoto This feature should be added in prerelease https://github.com/wileyyugioh/zotmoov/releases/tag/0.0.6b1. Let me know if you're having any problems

**Comment by mariashinoto** [comment]
I tested that. It works now. To be perfect, there are two points to mention:

1. The subfolder (which I create with the citekey) will not be deleted.
2. A snapshot is no longer recognized as a snapshot in the icon in Zotero. 

But it is useable now, a significant improvement. Thanks!

**Comment by wileyyugioh** [comment]
Yes, it is only for automatically moved files. The idea is that if you didn't want to the file to be moved while selecting them manually, you can just not select it.

If you're looking to convert your entire library I recommend doing an advanced search and saving it.

![Screen Shot 2024-03-16 at 15 16 59](https://github.com/wileyyugioh/zotmoov/assets/9703998/f891cc0a-d61b-499f-bef8-4ac1d9705884)

That way you can only convert pdfs, docx, epubs, etc.

**Comment by mariashinoto** [comment]
This is well-designed, thank you. So it is still possible to manually link other formats if necessary in certain cases.
