### ISSUE TITLE
html attachments (snapshots) cannot be re-converted to stored files

### ISSUE THREAD

**Issue by mariashinoto** [wileyyugioh/zotmoov#17]
When marking multiple entries to create linked files from stored files, snapshots (HTML) are also exported and linked. 

(1) When testing zotmoov, after linking files of entries, I used the `Tools > Manage Attachments > Convert Linked Files to Stored Files` command, which works well with PDFs and restores them in Zotero storage. However, snapshots (HTML files of a web page) are restored in a first step but immediately re-linked with file name addition ` 1`. I have to stop Zotmoov, manually return the file, and rename it to get snapshots back. 

(2) When linking snapshots, Zotero cannot check that they are snapshots (and cannot give them their icon), so I never get the snapshot icon back for these items.

(3) I would rather have snapshots kept in Zotero storage than linked together with PDFs. My last issue (https://github.com/wileyyugioh/zotmoov/issues/16) is with the above behavior in mind. 

Thank you very much for your work!

**Comment by wileyyugioh** [comment]
@mariashinoto This bug should be fixed in https://github.com/wileyyugioh/zotmoov/releases/tag/0.0.6b1. Let me know if it is still happening

**Comment by mariashinoto** [comment]
I tested that. It works now. To be perfect, there are two points to mention:

1. The subfolder (which I create with the citekey) will not be deleted.
2. A snapshot is no longer recognized as a snapshot in the icon in Zotero. 

But it is useable now, a significant improvement. Thanks!

**Comment by wileyyugioh** [comment]
When you say snapshot, do you mean one that is locally stored by Zotero, or one that is moved by ZotMoov? The icon not showing for files moved by ZotMoov is a limitation of Zotero and as far as I know cannot be fixed by me.

**Comment by mariashinoto** [comment]
I thought of the "snapshot" taken when a web page is clipped. It has another icon; I already thought that the information that this is a snapshot of a web page is only stored in Zotero and not easily retrieved with Zotmoov. So, when the file is returned to Zotero, it is only a simple HTML file. 

This is not a deal breaker. It reduces the meta-information that Zotero keeps when files are stored just in Zotero due to the linking, but the meta-information is not essential. I should consider either (a) tagging these snapshot files or (b) converting them into PDFs. The idea behind it is that I want to see where I have the actual reference at hand and where not. This was good with the snapshot icon. 

So far, regarding the background of my concern, it is not a dealbreaker, and Zotmoov works fine now.

**Comment by wileyyugioh** [comment]
Right, the file is still exactly the same as a snapshot html file, but the only difference is there's a little piece of information that Zotero stores that labels regular html files from the snapshot ones. So the icon appears for the html files that are created by the connector versus ones that are imported via other means.
