### ISSUE TITLE
Subfolder not deleted after unlinking files and deleting them with zotmoov

### ISSUE THREAD

**Issue by mariashinoto** [wileyyugioh/zotmoov#19]
When converting a linked file back to Zotero and deleting the file in the external folder as well, the subfolder is not deleted and stays empty in the folder for linked files. 

--> When converting a linked file to a file stored in Zotero, deleting the originally linked file in a subfolder, the subfolder should be deleted as well if empty. 

Thank you!

**Comment by wileyyugioh** [comment]
This coincidentally happens because of a new empty directory pruning feature added when a ZotMoov managed linked file is deleted. It will appear in an upcoming release
