### ISSUE TITLE
彻底删除附件后，在文件夹中pdf文件仍然保留

### ISSUE THREAD

**Issue by DereckZhang** [wileyyugioh/zotmoov#23]
当彻底删除文件（回收站中永久删除）后，附件仍然保留在链接的文件夹中，日积月累zotero中看不到“死链”文件会越来越多，建议回收站中彻底删除后，文件夹中对应的文件和目录也彻底删除，谢谢！

**Comment by redleafnew** [comment]
这个问题以前ZotFile也存在，删除时可以用插件：
导出附件，删除条目时删除附件，自动根据题目批量修改语言的插件：https://github.com/redleafnew/delitemwithatt

**Comment by wileyyugioh** [comment]
I have this feature in beta right now, and will hopefully release a new version with this feature in the upcoming weeks.

**Comment by redleafnew** [comment]
> Automatically Delete External Linked Files in the ZotMoov Directory

This setting could not be found in the preference of the latest beta version

**Comment by wileyyugioh** [comment]
> This setting could not be found in the preference of the latest beta version

Try 0.0.6b3. It was previously in the uncompiled source.
