### ISSUE TITLE
插件与同步功能存在冲突

### ISSUE THREAD

**Issue by DereckZhang** [wileyyugioh/zotmoov#24]
Zotero7最新版，插件最新beta版，设置为“新增时自动移动附件”并且File behavior 设置为MOVE，当新增一个Stored Files（此时软件开始将该文件上传到zotero服务器），同时，插件将Stored Files移动到靶目录并修改为Linked Files。于是本地和云端形成冲突，会跳出一个对话框问你保存本地还是云端。。
经过测试，先关闭软件自动同步功能，再添加文件，等插件移动完了再开启同步就不会有冲突问题，但这样就非常不方便，一旦添加很多文件，后面忘了开同步就会漏同步，建议插件增加一个移动前自动暂停同步，移动后再开启自动同步的功能，谢谢！

**Comment by wileyyugioh** [comment]
You can try unchecking "Sync attachment files in My Library" to fix this problem.
![Image3](https://github.com/wileyyugioh/zotmoov/assets/9703998/5c5321ac-28ac-4760-9839-82262309d570)

**Comment by DereckZhang** [comment]
> You can try unchecking "Sync attachment files in My Library" to fix this problem. ![Image3](https://private-user-images.githubusercontent.com/9703998/316122945-5c5321ac-28ac-4760-9839-82262309d570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExOTY4NzUsIm5iZiI6MTcxMTE5NjU3NSwicGF0aCI6Ii85NzAzOTk4LzMxNjEyMjk0NS01YzUzMjFhYy0yOGFjLTQ3NjAtOTgzOS04MjI2MjMwOWQ1NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMTIyMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA5OTU5MTNjYzkzMGU2MTMzMDIyOTQzYjU4M2UzYWEyMDMzNjY4MzE3ZDk1MzNiMmE1ZWM5ZmE3OWIzNWM0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJCyBt8JwCPmw-JcKhtIg8FQpQtC6gn0B1D8LN02HAE)

Thank you for your replay! This is a useful workaround for this problem, but if "Sync attachment files in My Library" is unchecked, (Zotero's native) notes can't be synced porperly. Images are not synced anymore because images in notes are seen as attachment files.

**Comment by wileyyugioh** [comment]
Can you try version 0.0.6b4 to see if this problem has been fixed?

**Comment by DereckZhang** [comment]
> Can you try version 0.0.6b4 to see if this problem has been fixed?

I have tried version 0.0.6b5, and find sync error has been fixed. This release can also automatically delete linked files after I delete them in Zotero. It meets all I need to replace Zotfile and it keeps simple and easy to use. Thank you again!
