### ISSUE TITLE
Request: Enable feature for shared libraries

### ISSUE THREAD

**Issue by kastnerp** [wileyyugioh/zotmoov#27]
I noticed this plugin only works for my personal library but not for shared group libraries. Is there a way to enable this?

**Comment by wileyyugioh** [comment]
Hi, please see [this](https://github.com/wileyyugioh/zotmoov/issues/15). The gist is that Zotero doesn't allowed for linked files in any library besides the personal one.

**Comment by kastnerp** [comment]
Got it, thanks! 

In case someone else sees this later: [This plugin](https://github.com/MuiseDestiny/zotero-attanger) allows me to move the group library files, but again, the links break immediately, as confirmed by @wileyyugioh.
