### ISSUE TITLE
Request: Wildcard for year added on zotero

### ISSUE THREAD

**Issue by ncarboni** [wileyyugioh/zotmoov#28]
Great extension! However, I am currently missing a (for me) quite useful wildcard. 

I would like to move the attachments to a specific directory and use zotmoov to organise the attachments based on the year I added them on Zotero. In the [ZotMoov Wildcard Formatting](https://github.com/wileyyugioh/zotmoov/blob/master/docs/WILDCARD_INFO.md) I could not find such option (only publication year `%y` ) and I was wondering if it would be possible to add such feature

**Comment by wileyyugioh** [comment]
Yes, it shouldn't be too much of an issue to add this feature. I'll put it in the next update.

**Comment by wileyyugioh** [comment]
Please try https://github.com/wileyyugioh/zotmoov/releases/tag/1.0.0.2

**Comment by ncarboni** [comment]
Works great! Thank you!
