### ISSUE TITLE
Move and link file when an item is imported

### ISSUE THREAD

**Issue by redleafnew** [wileyyugioh/zotmoov#3]
When I attach a PDF for a item or import an item from web such as ScienceDirect with attachment, could this plugin move and link file automatically?

**Comment by wileyyugioh** [comment]
Yes it should. The program hooks onto whenever an attachment is added to Zotero.

**Comment by redleafnew** [comment]
Perfect. 
Combined with https://github.com/Theigrams/zotero-pdf-custom-rename, the major function of zotfile could be  achieved.
