### ISSUE TITLE
Why recommend setting the Linked Attachment Base Directory (in Zotero Preferences) ?

### ISSUE THREAD

**Issue by TW96** [wileyyugioh/zotmoov#30]
I am unclear on why the current Zotmoov instructions need to recommend setting the Linked Attachment Base Directory (in Zotero Preferences) ?
People can have explicit-path linked file setups that do not need or use the LABD setting. For example if they only work on one computer, or if their linked attachments are at identical paths on all their computers. Zotmoov should work perfectly well with such setups.
The LABD only affects where Zotero *looks* for linked files when the user asks it to open a PDF in its reader. The LABD has no effect on where a new linked attachment gets stored - the thing that Zotmoov does. That is set by your "Directory to Move Files To".
But once a user does set a LABD in Zotero preferences, that changes how the linked file path is stored in the Zotero database. If done unnecessarily, that could break an existing expicit-path linked file setup. 
So to my mind, the Zotmoov instructions should omit any reference to the LABD setting. It deals with a separate issue. Zotmoov presumably functions in exactly the same way regardless of whether a LABD is set or not (does the Zotmoov code use the LABD setting for anything ?).
You could simply link to the Zotero instructions on the LABD, making it clear that it is only really needed for Zotero to find linked files on different computers when those files have different parent folder names.
Zotero users can get confused with linked file setups - for example the above difference between where the files get *stored* and where Zotero *looks* when opening them. Including the LABD in the plugin instructions doesn't help with that confusion.

**Comment by wileyyugioh** [comment]
The reason I included setting the Linked Attachment Base Directory is for a "fast-guide" for setting up third-party syncing services for multiple computers. Maybe I can move that information into a separate document to emphasize it is not necessary for setup/installation.

**Comment by wileyyugioh** [comment]
I updated the README to hopefully be more clear about using the linked attachment base directory and how it is not necessary for using the extension.

**Comment by TW96** [comment]
Perfect ! Thanks
