### ISSUE TITLE
Filename Format Does Not Follow Zotero Settings

### ISSUE THREAD

**Issue by heymaad** [wileyyugioh/zotmoov#31]
The plugin is supposed to follow the filename format according to what is set in the Zotero settings, but it is not. I have changed the default naming scheme from 
`{{ firstCreator suffix=" - " }}{{ year suffix=" - " }}{{ title truncate="100" }}`
to
`{{ authors max="1" suffix=" - " }}{{ year suffix=" - " }}{{ title truncate="150" }}`

However, the plugin still names the files according to the `{{ firstCreator suffix=" - " }}{{ year suffix=" - " }}{{ title truncate="100" }}` formatting.

**Comment by wileyyugioh** [comment]
Can you confirm this is a ZotMoov issue by testing it with the add-on uninstalled? The add-on uses the filename given by Zotero.

Also, do you mean the title, which is what is shown in the main Zotero panel next to the linked file icon, or do you mean the actual filename which is the name of the file in the file directory.

I tried your custom naming scheme on my computer and it seemed to work ok.

<img width="514" alt="Screen Shot 2024-08-04 at 22 36 53" src="https://github.com/user-attachments/assets/519b6350-77fb-43ad-ac73-0286593cca7d">

**Comment by wileyyugioh** [comment]
Have you enabled automatically renaming locally added files in the Zotero settings? I'm trying to recreate the issue but cannot.

**Comment by wileyyugioh** [comment]
Yes, ZotMoov copies the file from Zotero storage. So if the filename isn't correct in Zotero storage, that issue will propagate to the ZotMoov copy.
