### ISSUE TITLE
Switch to Zotmoov for Zotfile users

### ISSUE THREAD

**Issue by lfvasconcelos** [wileyyugioh/zotmoov#32]
What is the recommended procedure to switch to Zotmoov in Zotero 7 for users who use Zotfile in Zotero 6 and therefore already have linked files in a custom location (the filenames are the Zotfile default)?

**Comment by wileyyugioh** [comment]
ZotMoov shouldn't break existing Zotfile linked files. So you can put the ZotMoov data directory anywhere you want. The only thing that might break Zotfile is changing the linked attachment base directory.

**Comment by lfvasconcelos** [comment]
Thank you!

**Comment by BertLloyd** [comment]
@wileyyugioh might I suggest you add a "Switching from Zotfile" item to your Readme / FAQ with this information. I suspect that many others will be asking the same question now that Zotero 7 has fully arrived.
