### ISSUE TITLE
Request: Add Zotfile's Attach New File operation

### ISSUE THREAD

**Issue by TW96** [wileyyugioh/zotmoov#34]
As I understand it, Zotmoov does not currently include Zotfile's Attach New File option ?
In Zotfile, that right-click option looks to the nominated folder (not the same as the 'move to' folder) and finds the latest-dated file there (from the allowed file types list). It then asks the user if they wish to add that named file to the currently selected item (and move the file from that folder to the 'move to' folder as a linked file).
It is very useful when PDFs have to be added in ways other than automatically by the Zotero web connector (eg on sites where the connector fails to get the PDF and it has to be manually downloaded).

**Comment by deafmute1** [comment]
[Attanger](https://github.com/MuiseDestiny/zotero-attanger ) supports this feature.

**Comment by wileyyugioh** [comment]
If enough people want it I'll definitely consider adding the feature. But honestly I find just dragging the file from your browser's download window and dropping it onto the Zotero item to add files pretty easy already.

**Comment by talestomaz** [comment]
I used that Zotfile function a lot. I can certainly live with the dragging behaviour, but it would be a plus for me if Zotmoov would do that as well.

**Comment by wileyyugioh** [comment]
I added this feature to the [latest pre-release](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.0). Let me know if there are any problems with it.

**Comment by wangshengseee** [comment]
> I added this feature to the [latest pre-release](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.1). Let me know if there are any problems with it.

It's strange that when I use "attach new file" operation, the original downloaded pdf still exists in my "download“ file folder, although I have set File Behavior to "Move". It seems that the actual operation is still "Copy".

**Comment by TW96** [comment]
In Zotfile it is *always* a move. That seems to make most sense. You download a new file manually to the designated "Attach" folder, where it only lives temporarily (as the most-recently-dated file) until moved to the designated main, "Move to" linked-file folder.

**Comment by wangshengseee** [comment]
> In Zotfile it is _always_ a move. That seems to make most sense. You download a new file manually to the designated "Attach" folder, where it only lives temporarily (as the most-recently-dated file) until moved to the designated main, "Move to" linked-file folder.

Totally agree. So I'm confused this consequence should be owing to an inherent bug or wrong personal settings.

**Comment by wileyyugioh** [comment]
[1.1.8](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.8) now deletes the original file from the source directory and filters files based on the allowed file extensions setting.

**Comment by wangshengseee** [comment]
> I added this feature to the [latest pre-release](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.1). Let me know if there are any problems with it.

In Zotfile, conference papers from IEEE will be organized in a file folder named "IEEE", but in Zotmoov,  conference papers will be classified according to the conference name. As a result, there will be numerous file folders in my root directory, which is not prefered, I guess.

**Comment by wileyyugioh** [comment]
What is your subdirectory string?

**Comment by wangshengseee** [comment]
> What is your subdirectory string?

{%j}

**Comment by wileyyugioh** [comment]
I just checked a random IEEE conference paper in ZotFile and ZotMoov and it gives the same full conference name for %j. Maybe try %p/%j if you are concerned about your root folder being messy
