### ISSUE TITLE
Is there a way to "retrieve" a file back to my Zotero?

### ISSUE THREAD

**Issue by newterritories** [wileyyugioh/zotmoov#35]
Hi, I just upgraded to Zotero 7 and was sorry to see Zotfile is discontinued, so was keen to test out Zotmoov as a replacement. I've added the Zotmoov plugin, and see that I can select a file and "Move to Selected Directory", which is useful - but is there any way to "retrieve" that file document once I've finished reading it and it gets added back to the right location within my Zotero library, and adds a note of the annotations I made on the document? This was a wonderful feature of Zotfile, so really hoping I can replicate that workflow here. Is the main workaround just to do it manually? Thanks, Samantha

**Comment by jryans** [comment]
To move a file back to your local storage, you can use Tools menu -> Manage Attachments -> Convert Linked Files to Stored Files. I would also like to see a more natural option in the right-click menu, so perhaps @wileyyugioh will consider this issue as another vote for such a feature.

As for annotations, there’s no extraction to a note currently, but all the annotations of course remain accessible in Zotero’s reader.

**Comment by wileyyugioh** [comment]
I added this feature to the [latest pre-release](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.0). Let me know if there are any problems with it.

**Comment by TW96** [comment]
I believe that @newterritories is talking more broadly about Zotfile's Send to Tablet feature.

**Comment by jryans** [comment]
The new right-click "Convert Linked Files to Stored Files" seems to do the right thing, thanks for adding it. Although I know the name matches the built-in Zotero function you're invoking, I wonder if it would make sense to give the right-click menu item a better name in the context of Zotmoov...? For example, it could say "Move Selected from Directory", since it essentially does the opposite of the existing "Move Selected to Directory".

**Comment by wileyyugioh** [comment]
I updated the wording in the [latest pre-release](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.2).

And yes, jryan's reply is probably the best bet for getting the previous Move to Tablet functionality. The next release will have a menu item to make converting the files easier.

> To move a file back to your local storage, you can use Tools menu -> Manage Attachments -> Convert Linked Files to Stored Files. Only selected files will be converted. I would also like to see a more natural option in the right-click menu, so perhaps @wileyyugioh will consider this issue as another vote for such a feature.
> 
> As for annotations, there’s no extraction to a note currently, but all the annotations of course remain accessible in Zotero’s reader.

While ZotMoov has a lot of functionalities of ZotFile, it is not meant to be a complete clone. I want to keep it focused on the file moving aspect of ZotFile, so extracting the annotations to a Zotero note is unlikely to be a feature in the future.

**Comment by newterritories** [comment]
Hi @wileyyugioh , thanks for all the information and totally understand to just prioritize the file-moving functionality of Zotfile (not other things like extracting-annotations-to-note), and really appreciate it. One quick question just in case you have advice on this or anyone else does: 
- Before I upgraded to Z7, I had about 150 articles that I had used Zotfile to "send to tablet" and so they are sitting in my "Zotfile files" folder on Dropbox... as the functionality to "Get from tablet" is not possible anymore (and I have checked, there is definitely no "Convert Linked File" command available for these, which makes sense), do you have any recommendations on how to retrieve these files back to their "original" locations in Zotero library/file storage, so that I can go ahead and "Zotmoov: Move Selected to Directory"? I assume I can do this manually by: going through the Dropbox folder, and for each file, searching for it within Zotero, then dragging to that item, and then deleting the version in the Dropbox... but just curious if there are any other options I should consider?

**Comment by wileyyugioh** [comment]
The [latest beta version's](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) custom menu items enables users to replicate the Send to Tablet feature from Zotfile.
