### ISSUE TITLE
Request: step-by-step "for dummies" guide for switching from zotfile

### ISSUE THREAD

**Issue by BertLloyd** [wileyyugioh/zotmoov#36]
Hello, I am a long-time user of zotfile to move attachments to a Dropbox folder and create a link to the attachment. I would like to upgrade to Zotero 7, but am worried that without zotfile I will lose all the links. 

Would it be possible to provide in your FAQ a step-by-step "for dummies" guide to making the switch while keeping all links? I see that you gave a basic "no worries" in a now-closed issue but with a few thousand linked PDFs I am terrified that I will mess something up.

**Comment by wileyyugioh** [comment]
Does the [new entry in the FAQ](https://github.com/wileyyugioh/zotmoov/tree/beta?tab=readme-ov-file#migrating-from-zotfile) answer your questions?

How ZotFile works is basically converting your stored files into a linked file, which is a format Zotero itself supports. ZotMoov only modifies newly added files or ones you tell it to via the menu option, so it is very unlikely for the addon to break existing ZotFile linked files. Only thing that might break it is changing the linked attachment base directory, so as long as you don't touch it not much can go wrong.

To be safe though, make a backup before migrating!

**Comment by BertLloyd** [comment]
That looks great, thank you. I probably will not have time to make the switch until this weekend but I will post any comments or problems here if anything comes up.

**Comment by BertLloyd** [comment]
By the way I asked a similar question over at the Zotero forums but after a few hours assumed it had been rejected in moderation, I apologize if double-posting has annoyed anyone.

User tim820 over there had a helpful reply:

https://forums.zotero.org/discussion/comment/470754/#Comment_470754

**Comment by BertLloyd** [comment]
@wileyyugioh I have successfully upgraded following your steps, thanks.
