### ISSUE TITLE
Copying an Item that is in multiple Collections

### ISSUE THREAD

**Issue by heymaad** [wileyyugioh/zotmoov#37]
I have noticed that if an item is in multiple collections within Zotero, then the copying function doesn't work as expected. It should only copy that item from the opened collection to the folder of same name. However, it makes a new folder with name of other collections as well, and then only copies the pdf to the original collection. 

I would be okay if it copied the selected item to all relevant collections, but it only copies it from the collection where the file was saved initially.

I hope my explanation made sense. Happy to clarify further if needed.

**Comment by wileyyugioh** [comment]
I am planning to make it so that ZotMoov will prefer the collection that is opened in Zotero if an item is in multiple collections. I will post an update when the pre-release with this feature is released.
