### ISSUE TITLE
Request: Additional option for remaining the Attachment Title (instead of directly change it to the same as filename?)

### ISSUE THREAD

**Issue by 1qzhworld** [wileyyugioh/zotmoov#39]
First, thank you for your contribution to such a powerful tool. It helps me a lot in moving to Zotero 7. Currently, it works quite well for me and behaves just the same as the ZotFile functions. However, I found that the Zotero 7 developers recommended distinguishing the [Attachment Title and Filename](https://www.zotero.org/support/file_renaming#attachment_title_vs_filename). I also believe that it would be nice to show different titles for the attachment, which can provide more information.

However, currently, it seems that when moving the attachment with ZotMoov, the attachment name is also modified. This is a nice feature that helps people move to Zotero 7 (indeed, I also recommended this feature to friends). Nevertheless, is it possible to leave an option to keep the attachment name unchanged (such as "PDF" or "EPUB")?

Last but not least, I found that when an attachment becomes a link and is renamed with ZotMoov, the attachment title did not change (I use citationKey as the renaming rule, and after changing the citationKey and using move selected to directory with a right-click, the attachment title does not change). The two questions seem related, and I hope they can be solved. Thanks.

Feel free to ask if you need further clarification!

Best regards

**Comment by wileyyugioh** [comment]
> However, currently, it seems that when moving the attachment with ZotMoov, the attachment name is also modified. This is a nice feature that helps people move to Zotero 7 (indeed, I also recommended this feature to friends). Nevertheless, is it possible to leave an option to keep the attachment name unchanged (such as "PDF" or "EPUB")?

Funnily enough it used to be this way that the attachment name remained PDF or EPUB, but enough people wanted the old functionality I added it in. I will add in a hidden preference in the future to make it so the file title is unchanged.

> Last but not least, I found that when an attachment becomes a link and is renamed with ZotMoov, the attachment title did not change (I use citationKey as the renaming rule, and after changing the citationKey and using move selected to directory with a right-click, the attachment title does not change). The two questions seem related, and I hope they can be solved.

ZotMoov doesn't do the file renaming, but rather lets [Zotero 7 do the renaming](https://www.zotero.org/support/file_renaming). The wildcards are for defining the sub-directories to put the files in. If you want new files to be automatically renamed, enable ```Automatically rename locally added files``` in the Zotero general settings. For existing files you need to right click them and ```Rename File from Parent Metadata```.

**Comment by 1qzhworld** [comment]
Get it. Thank you for you support!

**Comment by wileyyugioh** [comment]
[1.1.8](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.8) now has the [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) ```extensions.zotmoov.rename_title``` to enable/disable custom title renaming over the Zotero default
