### ISSUE TITLE
adding batch move function

### ISSUE THREAD

**Issue by gaochuanchao** [wileyyugioh/zotmoov#4]
希望作者可以添加batch move的功能. 目前虽然可以使用batch move点击操作, 但似乎无法真正执行. 只有移动单个文件的时候, 文件移动才会真正执行.

**Comment by wileyyugioh** [comment]
Can you give an example of a file/files that don't batch move? I just tried it out on my machine and it worked fine.

**Comment by gaochuanchao** [comment]
now it looks ok and batch move works. not sure why i have the issue yesterday, maybe it is my mistake. anyway, thanks for developing this plugin.
