### ISSUE TITLE
Unable to move file via right-click menu

### ISSUE THREAD

**Issue by jryans** [wileyyugioh/zotmoov#41]
I just installed the latest [1.1.9](https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.9) release, and it seems to fail and log an error when selecting "Move Selected to Directory" from the right-click menu:

> [JavaScript Error: "TypeError: thisCache.zotmoov is undefined" {file: "jar:file:///Users/jryans/Library/Application%20Support/Zotero/Profiles/vny72kh7.default/extensions/zotmoov@wileyy.com.xpi!/src/03-zotmoov-menus.js" line: 57}]
load/<jar:file:///Users/jryans/Library/Application%20Support/Zotero/Profiles/vny72kh7.default/extensions/zotmoov@wileyy.com.xpi!/src/03-zotmoov-menus.js:57:13

**Comment by jryans** [comment]
When I downgrade to 1.1.8, it works again. So, it seems to be a regression that first appeared in 1.1.9.

**Comment by wileyyugioh** [comment]
Can you please try (1.1.10)[https://github.com/wileyyugioh/zotmoov/releases/tag/1.1.10] and see if the problem is fixed?

**Comment by jryans** [comment]
Yes, both 1.1.10 and 1.1.12 are working well, thanks! 😄
