### ISSUE TITLE
"Move Selected From Directory" grayed out

### ISSUE THREAD

**Issue by sternj** [wileyyugioh/zotmoov#45]
Under what circumstances is "Move selected from directory" not grayed out? It always seems to be grayed out for me, even when I've changed the file in the sync directory recently

**Comment by wileyyugioh** [comment]
Yes, it is meant to convert linked files back into Zotero storage. What did you expect the functionality to be @sternj? So I can see if I can change the wording/documentation to minimize confusion.

**Comment by sternj** [comment]
Well, I'm not entirely sure actually-- from what I've read, there are
- Stored files
- Linked files
- Files in the Zotmoov directory

The workflow that I want is:
- When a file in the Zotmoov directory is updated, it becomes visible in Zotero.
- (optional) when a file is added in Zotero, it is copied to the zotmoov directory

What I expect to happen is that, when there's a file in the Zotmoov directory corresponding to a given title, the "move selected from directory" either creates a new attachment or updates the existing one, perhaps with some "last modified" checks or whatever.

**Comment by wileyyugioh** [comment]
ZotMoov works the best the other way around. You add a file to Zotero--either by drag-and-dropping or the Zotero browser addon--and it'll convert the file to a linked file and will move the file to a user-defined directory.

The "Attach New File" option finds the last modified file in a directory and attaches it to an *existing* Zotero item. If you want to create a new item, probably best to [just create a new linked file directly](https://www.zotero.org/support/attaching_files#linked_files).

**Comment by sternj** [comment]
Wait a sec-- what I'm seeing is I can just copy the item out, rather than convert the stored file to a linked file. Is this because I installed Zotmoov on an existing library? Is there anything I can do about this?

**Comment by wileyyugioh** [comment]
I'm not sure what you are asking. If you want to convert the stored file to a linked file you need to make sure that the move option is selected in the settings. The copy option is for making backups of your pdfs that Zotero will not track.

**Comment by addy9908** [comment]
I am currently using copy option, and when I move references into a subcollection (subfolder), the Zotmoov folder will not update. Will it update if I use move option? Sorry I have not tried it out by myself because I do not want to mess up the database before getting some information here. Thanks.

> I'm not sure what you are asking. If you want to convert the stored file to a linked file you need to make sure that the move option is selected in the settings. The copy option is for making backups of your pdfs that Zotero will not track

**Comment by wileyyugioh** [comment]
@addy9908 The copy option is basically like a PDF backup option. Whenever you add a file to Zotero with the auto option enabled or use the menu item to Copy to Directory, it will copy only the PDF without touching the Zotero database. If you use the move option, it will move the file and also update the Zotero database to use linked files.

**Comment by addy9908** [comment]
Thanks for the help.
I actually tried to use move option today. But after I group some of my references into a subcollection, the folder inside the zotmoov directory does not update. I think this plugin only watch for new adds, but not grouping after you add your references.

> @addy9908 The copy option is basically like a PDF backup option. Whenever you add a file to Zotero with the auto option enabled or use the menu item to Copy to Directory, it will copy only the PDF without touching the Zotero database. If you use the move option, it will move the file and also update the Zotero database to use linked files.

**Comment by wileyyugioh** [comment]
> I think this plugin only watch for new adds, but not grouping after you add your references.

Yes, that's correct. If you want to move them to the folder after they have been added to Zotero you can use the right-click menu item.

**Comment by addy9908** [comment]
> > I think this plugin only watch for new adds, but not grouping after you add your references.
> 
> Yes, that's correct. If you want to move them to the folder after they have been added to Zotero you can use the right-click menu item.

I tried the right-click menu, which do make a new copy (not "move") inside the subfolder, but it will not delete the original file in the root. While for the pdf already inside the subfolder, it will make a new copy ended with "1". Can you add the option to really move the pdf from root to subfolder, and take care of the situation with pdf already inside the subfolder (prompt to choose skip, replace, or keep as a new copy option). Thanks.

**Comment by wileyyugioh** [comment]
If you want to make a backup of all of your pdfs, the best option right now is to just create a fresh new directory and copy them. If you want Zotero to be able to track the pdf location and move files around, best to use the move functionality instead.
