### ISSUE TITLE
Options for Subdirectories

### ISSUE THREAD

**Issue by nichhenr** [wileyyugioh/zotmoov#46]
Hi,
I just moved from Zotfile, where I had files in subdirectories named with multiple authors, not just the first. Is this possible in Zotmoov? It'd be nice to have the full set of renaming options / settings form Zotfile. https://zotfile.com/#renaming-rules

Similarly, right now I'm using the %F wildcard, but it'd be nice to have some other wildcards like author first initial so that you can have a separated author tag (e.g., Doe, J instead of DoeJ).

This might be possible already?--apologies if it is.

**Comment by nichhenr** [comment]
Great. Thanks!

**Comment by PKDmeDEV** [comment]
Does moving items within the Zotero affect the linking of Files in the Zotmoov's directory/child directory? Do you know if the link gets broken?

**Comment by wileyyugioh** [comment]
The [latest beta version's](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) custom wildcards enables you to customize the author's tag.

**Comment by nichhenr** [comment]
@wileyyugioh Thanks for the update! This will be great.

I am a bit unfamiliar with how to do the editing. I tried doing a RegEx replacement to get the %F tag, e.g., SmithJ, to look like "Smith, J." Can you walk me through how to do that?

Thanks so much for your help.

**Comment by wileyyugioh** [comment]
So first choose your custom wildcard. For example, %1.

Then press [+] and select the command ```text```.  Use the wildcard ```%F```.

Then press [+] again and select the command ```replace```. The regular expression is ```[A-Z]$``` and we want the replacement string to be ```, $&```. This essentially finds the last capitalized letter in the string and replaces it with a comma space and the same letter.

![Screen Shot 2024-11-13 at 15 01 42](https://github.com/user-attachments/assets/cdd5dc02-c492-4031-ab2c-0d5cb6ec0041)

The command isn't showing in the box cause of a UI bug, but it still works.
