### ISSUE TITLE
new function: customized file saving path

### ISSUE THREAD

**Issue by gaochuanchao** [wileyyugioh/zotmoov#5]
Hi, I am not sure whether following function can be added:
   

> add another move option to the right click manual:
         - allows user to choose the folder where he wants to store the file.  

   Note: I understand that this option exists in the setting window, but adding this to the right click manual make it more intuitive when saving files, especially when he wants to save some files to some special pathes. (if the workload is high, then just ignore this suggestion.)

<img width="284" alt="image" src="https://github.com/wileyyugioh/zotmoov/assets/22146315/1e1c8c30-c271-420a-9cf5-01de78f4dd4e">

**Comment by wileyyugioh** [comment]
I added the feature in the latest update https://github.com/wileyyugioh/zotmoov/releases/tag/0.0.2b. Try it out and let me know if there are any problems. You have to enable it in settings.

**Comment by gaochuanchao** [comment]
Hi, the option for customized saving path does not show up in the right click manual even i enable the function in the setting, not sure it is my PC issue or what.
![image](https://github.com/wileyyugioh/zotmoov/assets/22146315/5c70c0e4-b007-4b08-abd3-da0cb8472c49)
![image](https://github.com/wileyyugioh/zotmoov/assets/22146315/6ed1a81d-1688-4129-b296-c6fb0e794e36)

**Comment by wileyyugioh** [comment]
Can you try completely uninstalling the extension, restarting Zotero, and then installing the newest version? I fixed some bugs so redownload it. Also, I had some problems with Zotero's cache saving old files so maybe delete it if it doesn't work.

**Comment by wileyyugioh** [comment]
You can try the 0.0.02b version.

**Comment by gaochuanchao** [comment]
now it works, thanks for your help.
