### ISSUE TITLE
copying attached files doesn't seem to work for group library items

### ISSUE THREAD

**Issue by janneadolf** [wileyyugioh/zotmoov#51]
I was very happy to read that zotmoov's backup functionality is preserved for group libraries.
However, I can't seem to make the "copy selected to (custom) directory" options work for items in a group library I own. The 2 options are not greyed out, but clicking them has no effect. Copying works fine for items in my personal library.

zotmoov 1.1.14
Zotero 7.0.5
MS Windows 11 Pro 10.0.22631 Build 22631

**Comment by wileyyugioh** [comment]
Try setting the [hidden pref](https://www.zotero.org/support/preferences/hidden_preferences) ```extensions.zotmoov.copy_group_libraries``` to ```true```. I forgot to make it default to true and will fix this in a future update.

**Comment by janneadolf** [comment]
That fixes it - thanks for the prompt help!
