### ISSUE TITLE
Alternative method to pop-up-menu to trigger Zotmoove actions

### ISSUE THREAD

**Issue by dcgk** [wileyyugioh/zotmoov#54]
Hello, I really enjoy Zotmoove - it does everything I need.
Fantastic would be if there was another way to access the Zotmoove actions. Only being able to access these actions via the pop-up-menu is somewhat limiting, as I would like to add keyboard shortcuts to quickly move selected items from being externaly managed (linked) to Zotero internaly managed (attached). I have seen other Zotero plugins adding their commands to the Tools menu. Would that be possible? Or, is there another way, such as execution via JavaScript?

Thanks for the excellent plugin and many regards!

**Comment by wileyyugioh** [comment]
The [latest beta version](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) has the ability to define keyboard shortcuts.
