### ISSUE TITLE
Automatically move/copy from specific collection

### ISSUE THREAD

**Issue by SimoneCastellan** [wileyyugioh/zotmoov#57]
First of all, thank you for making this plugin, it is really useful.

My database on Zotero is quite big, I usually have project specific collections on my library. It would be nice to send to the tablet only the papers I'm actually using. I could do that manually, but having the automatic options would make it easier.  

If that's too much work, would it be possible to have an option to "move/copy to subdirectory when moving/copying to custom subdirectory"? This way, when I send the papers manually I would still have them divided by authors.

**Comment by wileyyugioh** [comment]
You can try the [latest beta version's](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) custom menu items. You can set it up so that it will move to the directory you specify.
