### ISSUE TITLE
Feature request: Disable the menu when there is no attachment

### ISSUE THREAD

**Issue by redleafnew** [wileyyugioh/zotmoov#6]
Could the context menu be diabled when there is no attachment?
Like this: 

![image](https://github.com/wileyyugioh/zotmoov/assets/22135631/8c364c2b-24bb-4971-ae68-8cbb0a190eb0)

**Comment by wileyyugioh** [comment]
I will look into it, and if it's not too difficult will implement in next version.

**Comment by redleafnew** [comment]
Thanks.

**Comment by redleafnew** [comment]
!!!
Thanks.

**Comment by wileyyugioh** [comment]
Added in latest update
