### ISSUE TITLE
Feature Request: Option to remove or replace spaces in the folder names

### ISSUE THREAD

**Issue by red-associations** [wileyyugioh/zotmoov#60]
Hi,

I've just started setting up zotmoov and noticed that the resulting folder names have spaces in them.

Would it be possible to have the option to either remove or replace the spaces? If I remember correctly zotfile had that option.

Thanks in advance!

**Comment by wileyyugioh** [comment]
Yup. I'm working on a big 1.2 release where one of the new features is custom wildcards that allow you to do things such as replace spaces. Please be patient as I work on it!

**Comment by wileyyugioh** [comment]
You can try the [latest beta version's](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.0) custom wildcards. You can use the regex ```replace``` to remove/replace spaces.
