### ISSUE TITLE
.html attachments not renamed when "attach new file"

### ISSUE THREAD

**Issue by notuntoward** [wileyyugioh/zotmoov#61]
I have enabled zotmoov's setting to "automatically move/copy files when added", and I also have html in my list of "allowed files extensions."  However, when I run "Zotmoov: Attach New File", the file is moved and attached as expected but neither the new attachment filename or title are renamed from metadata.

Should I expect this to happen?

**Comment by wileyyugioh** [comment]
Zotmoov uses Zotero's default renaming scheme under the hood, and it seems like [it doesn't support html](https://forums.zotero.org/discussion/119126/rename-html-too). Maybe you can try the fix [here](https://forums.zotero.org/discussion/116925/how-to-automatically-rename-attached-html-files)?

**Comment by wileyyugioh** [comment]
> So does that mean there are effectively two levels of file type permissions when zotmoov moves/renames an attachment - one for which file types get moved (zotmoov's allowed list) and another for what file types get renamed (Zotero's list) ? 

Yes basically. Importing any file uses the default Zotero renaming feature, but whether or not the file is later moved/copied is done by zotmoov's settings. When you import a file using attach new file, zotmoov does the same checks Zotero does to see whether or not the file should be renamed to ensure consistency.

**Comment by franciscowilhelm** [comment]
This issue is closed, but I was wondering if the situation has changed in the latest Zotero 7.1-beta? For an .xlsx file (the original here discusses a .html), I can "rename file from parent metadata", but I cannot move an excel to directory via "Move selected to directory". This would be nice to do as more and more papers contain additional data in teh form of .xlsx or other file types.

**Comment by wileyyugioh** [comment]
@franciscowilhelm have you added xlsx to the allowed file extensions?
