### ISSUE TITLE
Doesn't work when importing a linked file?

### ISSUE THREAD

**Issue by mjbaldwin** [wileyyugioh/zotmoov#64]
I add my PDF's as links, because I actually keep them in Google Drive, where I've set the base directory both in Zotero and as the "Directory to Move Files To" in ZotMoov.

On my Mac, I Cmd+Shift+drag a PDF file from Finder onto the item in Zotero. This creates a link to the file.

I installed ZotMoov because I thought this was supposed to then automatically move the PDF file from whatever folder it was in, to my desired base directory. And I have "Automatically Move/Copy Files when Added" checked, and "File Behavior" is set to "Move".

But it doesn't move the PDF at all when I Cmd+Shift+drag it in.

I have to right-click the file, then select "ZotMoov: Move Selected to Directory" and then it moves it correctly.

Is this intended behavior or is it a bug? Is ZotMoov supposed to work when importing files as links rather than attachments?

**Comment by wileyyugioh** [comment]
It is intended behavior that any added linked files is not moved. Only regular stored files are automatically processed by ZotMoov. To clarify, if you drag-and-drop a file into Zotero, it will convert the stored file into a linked file and then move it into your Google Drive. So there is no need to first add it to the Google Drive and then add it to Zotero as a linked file if you are confused about that.

**Comment by mjbaldwin** [comment]
Ah thank you, sorry. I see how it works now, thank you -- so the concept is to drag it in as if it were an attachment, and then ZotMoov does the linking for me.

I continue to be confused by something, then. I just tried dragging a PDF in my Downloads folder (outside my Google Drive) into Zotero, and I watched it get converted into an attachment that is now renamed and sits in my Google Drive folder (perfect!).

However, the original PDF file is still sitting in my Downloads folder. But my settings are set to Move:

<img width="588" alt="image" src="https://github.com/user-attachments/assets/5e569ce6-99f2-45ed-8284-b9826ec03bda">

Is this not supposed to move the file from my Downloads folder, into my Google Drive? It seems that it copied it instead. Thank you if you're able to answer.

**Comment by wileyyugioh** [comment]
It moves it from the internal Zotero storage to your Google Drive. When you drag-drop a file the process goes like:

copy the file to Zotero -> move the copied file from Zotero storage to Google Drive -> update the Zotero database to a linked file and point to the correct directory.

The only operation where files are removed outside of the Zotero directory is attach new file.

The copy behavior is for making back-ups of your PDFs. So if you drag-drop a file it will just make a copy of the file into another directory without touching Zotero's internal storage or database.

**Comment by mjbaldwin** [comment]
Ah thank you for the explanation! I think I understand ZotMoov's conceptual model now.

Can I suggest two things then, in case they're helpful?

1) In case other people get as confused as I was, it might be helpful to explain all of this more clearly in the readme -- since there are 3 possible file locations rather than 2 (original, Zotero attachment, destination folder), it is not clear which ones "copy" and "move" refer to. And because there are two possibilities of dragging (regular as an attachment, or Cmd+Shift as a linked file), it's not clear which one ZotMoov is designed for, or which one you're supposed to use for ZotMoov to work

2) And if it's possible, to support an option for "move" from original folder to destination, that removes the file that was originally dragged in. Once I move something into Zotero I never want to keep the PDF in my Downloads folder, so it would be a nice bonus if that could get deleted once the file is safely in my destination (Google Drive) folder

In any case, thanks for the extension. It's certainly faster than having to find my destination folder and move the file manually to it each time I import a PDF, so I appreciate it!

**Comment by mjbaldwin** [comment]
> The only operation where files are removed outside of the Zotero directory is attach new file.

Oh, and I realize I don't know what you mean by this. Because when I attach a file by dragging it in (without Cmd+Shift), the file isn't removed.

**Comment by wileyyugioh** [comment]
> Oh, and I realize I don't know what you mean by this. Because when I attach a file by dragging it in (without Cmd+Shift), the file isn't removed.

I meant the [attach new item menu option](https://github.com/wileyyugioh/zotmoov/blob/master/docs/SETTINGS_INFO.md#source-folder-for-attaching-new-files).

**Comment by mjbaldwin** [comment]
> I meant the [attach new item menu option](https://github.com/wileyyugioh/zotmoov/blob/master/docs/SETTINGS_INFO.md#source-folder-for-attaching-new-files).

Ah thank you! I didn't even have that option in my menu, turns out I had to enable it in the plug-in settings.

That option is incredibly helpful -- it even automatically finds the right file!

I never would have found it if you hadn't pointed it out.

Thanks again for your help. Your extension is very helpful and appreciated. I do hope you can update the documentation to reflect what ZotMoov does in each case, because there are so many different ways of attaching and linking, and ZotMoov intercepts some of them but not others, and moves in some cases but copies in others, and I never could have figured it out without our conversation here.

Cheers!
