### ISSUE TITLE
"Move from" context menu item fails with error

### ISSUE THREAD

**Issue by jryans** [wileyyugioh/zotmoov#66]
Thanks for all your work, overall the new beta version seems to be coming together well! 🙂 

When testing 1.2.1 today, I noticed that selecting an attachment and using the "move from directory" context menu item fails. 

The Zotero error console says `moveFrom is not defined` at `02-zotmoov.js:352`. Maybe it should be `this.moveFrom`...?

**Comment by wileyyugioh** [comment]
This bug should be fixed in [1.2.2](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.2). Please let me know if this is not the case.

**Comment by jryans** [comment]
Thanks, this is indeed fixed in 1.2.2!
