### ISSUE TITLE
sync on ipad

### ISSUE THREAD

**Issue by shannon-hou** [wileyyugioh/zotmoov#70]
Hi,
I have three devices: a Windows PC, a MacBook, and an iPad. I’ve managed to set up syncing on my PC and MacBook through onedrive using the Zotmoov extension. However, I’m having trouble syncing on my iPad since I can’t install the extension there, and I don’t see any related settings on my PC. I have downloaded onedrive and zotero on my ipad.

Could you please provide advice on how to sync between my PC and iPad? Thank you in advance!

**Comment by wileyyugioh** [comment]
The Zotero mobile apps don’t support linked files, so ZotMoov won’t work with them. Your alternatives are the official Zotero sync service or WebDAV.

**Comment by shannon-hou** [comment]
> The Zotero mobile apps don’t support linked files, so ZotMoov won’t work with them. Your alternatives are the official Zotero sync service or WebDAV.

Thanks! I tried WebDAV method and used koofr to configure WebDAV for OneDrive. It works well!
