### ISSUE TITLE
Feature request - Option to remove "zotmoov" tag

### ISSUE THREAD

**Issue by yihao-liang** [wileyyugioh/zotmoov#72]
Hi,

Thank you for your excellent work on zotmoov! I noticed that items automatically moved by zotmoov are tagged with "zotmoov" by default.

Would it be possible to add an option to remove or disable this tagging?

Thanks again for your efforts and consideration!

**Comment by wileyyugioh** [comment]
There is a [hidden preference](https://github.com/wileyyugioh/zotmoov/blob/master/docs/SETTINGS_INFO.md#selected-hidden-preferences) you can change.
