### ISSUE TITLE
Zotmoov menu entries greyed out

### ISSUE THREAD

**Issue by sereios** [wileyyugioh/zotmoov#74]
Alfter installing Zotmoov from file, all functionality is greyed out.

I am working on MacOS Sequioa.

I set the directory (to `<my_user_directory>/sciebo/Forschung_cloud/6_Literatur/PDFs` which is in the same parent directory as my Zotero directory) as specified, but when I right-click an attachment, all Zotmoov entries are greyed out.

From the Documentation, it seems I have done everything I need. Restarting Zotero does not change anything.

I am not sure what I am missing. Is there some setting I have overlooked?

I am happy to provide more information on my setup, if needed.

**Comment by wileyyugioh** [comment]
Is it in a group library? Can you send some screenshots?

**Comment by sereios** [comment]
> Is it in a group library?

Actually, that already solved the problem. I had not thought about that yet: Indeed, they are. The entries are in a synchronized group library (which is not supported of course). When I change behaviour to "copy" or move files into my personal library, it works as expected.

Thank you!

Are you planning to support group libraries in the future?

**Comment by wileyyugioh** [comment]
Unfortunately no support for linked files in a group library is a [Zotero limitation](https://www.zotero.org/support/attaching_files#linked_files), so it will unlikely be supported in the future. The copy feature should still work though.
