### ISSUE TITLE
ZotMoov replaces terminal period in journal abbreviations from {%s} with an underscore

### ISSUE THREAD

**Issue by nickuhlig** [wileyyugioh/zotmoov#75]
If using {%s} in ZotMoov's subdirectory, journal abbreviations that end in a period will convert that terminal period to an underscore.

For example:
1. The journal Organic Letters abbreviates to Org. Lett.
2. Subdirectory string is /{%s}/{%y}/
3. ZotMoov places articles in a folder "/Org. Lett_/{%y}" instead of "Org. Lett./{%y}"

It is not clear why this happens. Using Zotfile under Zotero 6 this was never an issue, but now it appears to consistently happen when journal abbreviations end in a period.

**Correction**: in Zotfile under Zotero 6, it actually _removed_ the terminal period. Is there any way we can get this behaviour back?

**Comment by wileyyugioh** [comment]
By default ZotMoov replaces all invalid characters (like a period at the end of a directory) with underscore. You can use custom wildcards to get around this. Just replace %s with %1.

![Screen Shot 2024-12-19 at 16 03 14](https://github.com/user-attachments/assets/771c95f2-72df-4259-8108-60e5c807f5c8)

Note that you have to be on the latest version (1.2.10) for this to work.

**Comment by nickuhlig** [comment]
after updating to current version, this works perfectly. thank you for the explanation.
