### ISSUE TITLE
Bulk moves stopping prematurely

### ISSUE THREAD

**Issue by dhicks** [wileyyugioh/zotmoov#77]
I'm trying to use ZotMoov to relocate a large number of PDFs files.  The move process appears to stop partway through, though it's difficult to tell what's actually happening. 

Context: I've decided to move my PDF storage out of Google Drive.  I have about 12,000 PDFs that need to be moved.  To break this into chunks, I set up an advanced search that uses Date Added tests and Attachment File Type to list, eg, all of the items with PDFs that I added in 2015. This particular search returns 1,470 top-level items. There will be somewhat more PDFs to actually move (because some items have multiple PDF attachments.) 

I select-all, bring up the context menu, and set Move Selected to Directory.  Individual PDF attachments are highlighted, one at a time.  This continues for 1-10 minutes, and then stops.  From what I can tell, once the process stops, all of the PDFs that have been highlighted have been moved; some other PDFs have also been moved; and some have not been moved. Sometimes the attachments are highlighted in the order they're shown in Zotero (Date Added, descending order) and sometimes not.

**Comment by wileyyugioh** [comment]
Can you check the Zotero error console to see if anything pops up? Where are you moving the files to? The code usually ends prematurely if there’s any problem copying the files over.

**Comment by wileyyugioh** [comment]
Also can you confirm that ctrl-a is selecting all of the files? It’s interesting to me that only the highlighted files are being moved.

**Comment by dhicks** [comment]
The Zotero error console shows only this message, which appears at the start of an attempt: `12:18:26.456 TypeError: file_path.split is not a function 02-zotmoov.js:172:42` 

I'm moving the files from a folder in my local Google Drive sync (`~/Google Drive/Zotero/attachments/<author1>/<author1-title>.pdf`) to another, non-synced folder in my user directory (`~/Zotero_pdfs/<author1>/<author1-title>pdf`). 

I might not have explained clearly the highlighting/selecting behavior I'm seeing.  I hit command-A to select everything (all the top-level items) in the saved search. Everything is highlighted, as you'd expect.  Then ZotMoov (or something else) takes control of selection, and selects one PDF attachment at a time. Does that make sense?

**Comment by wileyyugioh** [comment]
Are all your files downloaded to your computer? Also do files get moved after you see the error message, or does it stop running then.

**Comment by dhicks** [comment]
Yes; I sync the entirety of my Google Drive locally.  The error message shows up almost immediately after I start an attempt, and it appears to run for another ~1 minute after that. 
-----
Dan Hicks
Associate Professor and Chair
Department of Philosophy
University of California, Merced

Pronouns: they/them/their

**Comment by wileyyugioh** [comment]
Try [1.2.11](https://github.com/wileyyugioh/zotmoov/releases/tag/1.2.11)

What I suspect is happening is that there is some invalid file path in one or more of your Zotero entries that is causing the code to crash. Files that are processed before the crash continue to be moved afterwards due to concurrency headaches. What this update does is skip over the invalid entries and continue moving all the valid files.

**Comment by dhicks** [comment]
This seems to be working!  I'll go ahead and close the issue, and follow up tomorrow if it turns out things are unresolved. Thanks!
